### ISSUE TITLE
Problems using with NF 2014.1.14.2

### ISSUE THREAD

**Issue by willgroove** [AddedInnovation/nf-gdpr-extension#1] opened 2019-03-29 20:12 UTC
Love this extension idea! 

Evidently, our version of NF, 2014.1.14.2 is different than the version targeted by this extension. The schema is a mismatch in two columns:
Invalid column name 'dys_queryparam_flag'.
Invalid column name 'dys_readonlydb_flag'.

I commented out these two columns from the MD script, and it completed successfully.

Then ran the extension by pressing the button, and found there's a mismatch in (at least one) method call:  
Exception of type 'System.Web.HttpUnhandledException' was thrown.; Method not found: 'Avectra.netForum.Common.NfDbConnection Avectra.netForum.Data.DataUtils.GetConnection()'.

I'm attaching output files.

[AI_GDPR_Ext_MD_output.rpt.txt](https://github.com/AddedInnovation/nf-gdpr-extension/files/3024340/AI_GDPR_Ext_MD_output.rpt.txt)
[AI_GDPR_Ext_RuntimeError.txt](https://github.com/AddedInnovation/nf-gdpr-extension/files/3024343/AI_GDPR_Ext_RuntimeError.txt)

Thanks!
Bryan P

**Comment by davidschlum** [comment] 2019-04-09 18:48
@willgroove can you send me your data.dll so I can ensure I get the right GetConnection() overload that will work across versions?

**Comment by willgroove** [comment] 2019-04-10 19:40
here is the data dll ...
[data.zip](https://github.com/AddedInnovation/nf-gdpr-extension/files/3065551/data.zip)

**Comment by davidschlum** [comment] 2019-04-12 15:49
@willgroove it looks like your version of the data.dll has a new optional parameter vs what we are building our packages with. Probably the easiest thing for you to do on this one would be to fork this repo and check in your data.dll and build. Then, you can use your build for your environment. Does that work for you?

**Comment by willgroove** [comment] 2019-04-12 17:22
@davidschlum Sure, that works. I was able to get this to work locally by replacing references to NF v2017 dlls with references to NF v2014 dlls, rather than switching them out one at a time. 
(When I get a few minutes, I'll try to fork and check in, though I'm not as well versed in Git as I am TFVC, so it may not be right away.)

**Comment by davidschlum** [comment] 2019-04-12 18:16
Great! Let me know if you run into any issues.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mwhisler** [comment] 2020-02-06 23:53
Looks like the issue is resolved so I'm going to close this.

**Closed as completed by mwhisler** 2020-02-06 23:53 UTC
Labels: bug, good first issue
